#!/bin/bash
#
# Launch a GTK+ application to the Broadway display server


error(){
    # detect TTY and respond appropriately
    if [[ -t 0 ]]; then
        echo "ERROR: $*" >&2
    else
        zenity --error --text="$*" --title=broadway-launch &>/dev/null
    fi
}


have(){
    hash "$1" &>/dev/null
}


is_daemon_running(){
    pgrep -u "$USER" -x broadwayd &>/dev/null
}


# determine display at runtime
DYNAMIC=1

# default value (this will be updated at runtime if DYNAMIC is enabled)
BROADWAY_DISPLAY=':1'

# check whether broadwayd is running and launch it if necessary and possible
if ! is_daemon_running; then

    if have broadway-daemon; then

        if [[ -t 0 ]] || ! have xfce4-terminal; then
            # launch daemon in background or current terminal
            broadway-daemon &
        else
            # launch daemon in new xfce4-terminal window
            xfce4-terminal --command='broadway-daemon' --title='broadway-daemon' &
        fi

        # wait one second before continuing
        sleep 1

        # ensure daemon was successfully launched before continuing
        if ! is_daemon_running; then
            error "broadwayd is not running (failed to launch 'broadway-daemon')"
            exit 1
        fi

    else
        # exit because broadway-daemon is not installed
        error "broadwayd is not running (consider installing and running 'broadway-daemon')"
        exit 1
    fi

fi

# request args via GUI if necessary
if (( $# == 0 )); then
    output=$(zenity --cancel-label=Close --entry --ok-label=Launch --text='Command:' --title=broadway-launch 2>/dev/null)
    eval set -- "$output"
fi

# exit if no args
(( $# == 0 )) && exit 1

# save original arguments
args=("$@")

if (( DYNAMIC == 1 )); then

    pid=$(pgrep -u "$USER" -x broadwayd 2>/dev/null)
    cmd=$(ps -o cmd= "$pid" 2>/dev/null)
    eval set -- "$cmd"

    shift
    while [[ -n $1 ]]; do
        case $1 in
            --address)
                shift
                BROADWAY_ADDRESS=$1
                shift
                ;;
            --port)
                shift
                BROADWAY_PORT=$1
                shift
                ;;
            --unixaddress)
                shift
                BROADWAY_UNIXADDRESS=$1
                shift
                ;;
            --)
                shift
                ;;
            --*)
                shift 2
                ;;
            *)
                BROADWAY_DISPLAY=$1
                shift
                ;;
        esac
    done

fi

BROADWAY_DISPLAY="$BROADWAY_DISPLAY" GDK_BACKEND=broadway "${args[@]}"
